### ISSUE TITLE
[Feat Request] Validate partials

### ISSUE THREAD

**Issue by hefler** [celian-rib/vscode-webvalidation-extension#11]
It would be nice if this extension also validated HTML partials (without `html`, `head` and `body` tags).

All this tags could be "implied" if not present in an HTML document.

**Comment by celian-rib** [comment]
I @hefler , do you have a file as an example ?

**Comment by hefler** [comment]
Let's say this is an HTML file called `partials.html`.
```HTML
<div>
    <header>
        <h1>HTML5 Partials</h1>
        <h2>Small bits of HTML</h2>
    </header>
    <main>
        <p>This is a perfect "validatable" piece of HTML code that fails get validated.</p>
        <p>Yet validating partials such as this can be useful. :)</p>
    </main>
</div>
```
Then in the extension preferences having something like:
> #### Validate partials as:
> - [x] HTML5
> - [ ] XHTML
> - [ ] HTML4
