### ISSUE TITLE
Unknown Error occurred

### ISSUE THREAD

**Issue by itsjaniahmed** [celian-rib/vscode-webvalidation-extension#13]
### Unknown Error occurred

I don't know when happens, But when I opened vs code today And clicked on 'w3c validation' for validation it asked me an error occurred. Also, I don't install any extension or not change any config.
It worked fine last night.

![Capture](https://user-images.githubusercontent.com/62384867/120420691-47a19700-c37e-11eb-8ecb-ceaf74ce41c5.PNG)

**My internet and also all other things work perfectly.
**Please check!****

**Comment by celian-rib** [comment]
Hi @itsjaniahmed , does the error still persist? It may have been an issue with the W3C API.
If not i'll do more research.
Thanks for submitting this issue.

**Comment by itsjaniahmed** [comment]
Hi @celian-rib, Thanks for replying. 
I rechecked, But still doesn't work on my laptop. I think it's due to some sort of clash between some extensions or their updates, I am checking which is the exact problem.
Because I also checked on another laptop and it is working there. 

Thanks Again.
Regards!!

**Comment by maycalle** [comment]
I have the same problem and I have not been able to fix it. I have tried uninstalling the extension and reinstalling it, but it still doesn't work. I only have one extension installed ("Open in browser") but I don't think there is a conflict between them.

Any ideas to fix it?

Thanks in advance.

**Comment by itsjaniahmed** [comment]
Hi,
Try to uninstall vs code and then install a new version of vs code and then install the extension.
Then, It should work.
