### ISSUE TITLE
Can the extension be made to check php pages too?

### ISSUE THREAD

**Issue by pboulton** [celian-rib/vscode-webvalidation-extension#15]
The validator at https://validator.w3.org/ allows php pages to be checked for html validation but your VSCode extension says "Not an html or css file".  Is there any way your extension could be tweaked to allow validation of the html content of php files?

Thanks!

Pete

**Comment by celian-rib** [comment]
I'll try :)

**Comment by celian-rib** [comment]
@pboulton The w3c validator accept only these types of files : 
![image](https://user-images.githubusercontent.com/38594012/132065092-690f5b59-75b6-4ddc-b16e-a2e1a7f3025f.png)

And yet only html and css are implemented in the extension.
I guess you are talking about the generated html or xhtml
I will need to take a deeper look into php :)
