### ISSUE TITLE
W3C Extension: "An error has occurred."

### ISSUE THREAD

**Issue by thboon3** [celian-rib/vscode-webvalidation-extension#21]
Hi, 

I've installed the extension by recommendation of my teacher to validate my html files. However, when I try to run it, I receive the message: "An error has occurred." See the below image: 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/91262513/150646057-8d0e25e6-ba6b-40b0-98de-43cfd32ccf8e.png">

I just clicked on the on the blue check mark on the bottom left and this happened. Any idea how to solve this? My teacher says I have several mistakes in my file but I need to validate to find them.

**Comment by celian-rib** [comment]
Hi @thboon3 , the w3c validation service is actually down.
I can do nothing about that, we just have to wait :/

[If this URL works then you should be good to go !](https://validator.w3.org/check?uri=https%3A%2F%2Fsilant.net&charset=%28detect+automatically%29&doctype=Inline&group=0)

Thank you for reporting, and good luck with your studies ! :)

**Comment by nikar** [comment]
@celian-rib I also tried to use your validator (I liked it a lot, I have used it earlier) and I still got the same error. 
W3C validation service is doing ok, the problem is not there....

Best Regard, Kari

**Comment by nikar** [comment]
@celian-rib Now it works again! Great!

**Comment by celian-rib** [comment]
> @celian-rib Now it works again! Great!

Glad to hear that! Thanks for submitting the issue!
