### ISSUE TITLE
No extension button

### ISSUE THREAD

**Issue by ChrisJohnNewton** [celian-rib/vscode-webvalidation-extension#27]
I have installed the plugin and it is enabled, however, I cannot find the extension button to run the HTMl validation. I have relaunched VSCode and have a HTML file open, but the extension button is not present. Any ideas how I can fix it? Thanks!

![Screenshot 2022-07-07 at 12 02 15](https://user-images.githubusercontent.com/87365058/177758678-791107c1-3ed4-460d-9196-20f774f2ec8c.png)

**Comment by ChrisJohnNewton** [comment]
PS. I am able to use the plugin and it's working well, but the shortcut button would be nice!

**Comment by celian-rib** [comment]
Hi @ChrisJohnNewton, thanks for posting this issue.

Have you tried to toggle the vscode status bar? 
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/38594012/177950518-af18d74c-9867-4537-bf9e-937acbbfc4e4.png">
