### ISSUE TITLE
more detailed notification

### ISSUE THREAD

**Issue by champignoom** [celian-rib/vscode-webvalidation-extension#32]
The first validation attempt lasted for 1min showing "W3C validation ..." and ended up with "An error has occured". I guess it's because of some online connection either for downloading the validator or for the validation itself.

The second attempt succeeded, so this is not a major issue.

But it would still be helpful to clarify the notification if it's doing anything online, otherwise it would be confusing why "W3C validadtion ..." takes 1min for an empty html.

**Comment by celian-rib** [comment]
Hi @champignoom thanks for your issue.
Since the validation is done entirely online through the W3C API, having good network conditions is necessary.
