### ISSUE TITLE
doctype in lowercase creates validation errors

### ISSUE THREAD

**Issue by ripcorddesign** [celian-rib/vscode-webvalidation-extension#33]
"DOCTYPE"
validates

"doctype" (<!doctype html>)
errors

**Comment by celian-rib** [comment]
Hi @ripcorddesign, the DOCTYPE tag is case indeed not case-sensitive as related by W3C
https://www.w3.org/TR/2010/WD-html-markup-20101019/syntax.html#doctype-syntax

But it seams like the W3C validation API is not working as expected for this special case.
I'm afraid I can't do much about it.

Thanks for reporting this issue!

**Comment by ripcorddesign** [comment]
Understood. Odd that it seemed to work fine prior to just recently (the past few months).
