### ISSUE TITLE
Stray doctype error.

### ISSUE THREAD

**Issue by Electricz0** [celian-rib/vscode-webvalidation-extension#34]
Currently, the extension (only version 1.3.0) is telling me that truly valid HTML is actually invalid. I keep getting errors that seem to indicate that the HTML from my file is getting wrapped inside the body of another HTML file before being validated, so a bunch of stray tag errors show up. See below to get an idea of what I mean.

HTML code such as this:

```HTML
<!DOCTYPE HTML>
<html lang="en">
<head>
    <title>Untitled</title>
</head>
<body>
	
</body>
</html>
```

Will get errors like this:

![html_validator_errors](https://user-images.githubusercontent.com/12022661/231276873-3e5b63e0-8715-447f-b47e-db37cfb392d8.jpg)

Even though the official validator will say this:

![2023-04-11 16_09_31-Showing results for contents of text-input area - Nu Html Checker — Mozilla Fire](https://user-images.githubusercontent.com/12022661/231277344-284b82a6-6d4e-4771-84b3-a068027d28de.jpg)

**Comment by avimalhotra** [comment]
Facing same issue. Extension is showing errors but actually there are no issues.

 
<img width="757" alt="Screenshot 2023-05-01 at 7 00 04 PM" src="https://user-images.githubusercontent.com/16258265/235458441-dc2fc91d-cd79-40e3-9569-0f72b5c9a5f4.png">

**Comment by avimalhotra** [comment]
Got the solution.
Just replace doctype with DOCTYPE. 
The problem is with doctype is lowercase. 
<!DOCTYPE html> works perfectly.


<img width="350" alt="Screenshot 2023-05-14 at 2 00 01 PM" src="https://github.com/celian-rib/vscode-webvalidation-extension/assets/16258265/3f96cfb9-7769-43ca-96aa-6aee41ed3f3a">

**Comment by AdeVedA** [comment]
Sorry to comeback on the subject, (it may be another problem) but none of my html files are recognized as valid (whereas W3C Web Validator works fine on css).
Notification tells "Not an HTML or CSS file.". The tested html files are using django 5.1.1 and bootstrap 5.3.3, i tried on base html and partials, none are told to be html files (but well... they are indeed ! and "!DOCTYPE html" is not lowercase). Did i miss something ?
